import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import kitchenImg from "../../public/kitchen.png";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>de Bem Brothers</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen">
        <div className="absolute -z-10 max-h-screen w-screen">
          <div className=" relative from-[#00000095] to-[#00000000] after:absolute after:left-0 after:top-0 after:h-screen after:w-full after:bg-gradient-to-b after:opacity-90">
            <Image
              src={kitchenImg}
              alt="kitchen"
              className="h-screen w-full object-cover"
              quality={100}
            ></Image>
          </div>
        </div>
        <h1 className="ml-[10%] mt-[10%] text-[10vw] font-bold text-white leading-[10vw]">
          de Bem
          <br /> Brothers.
        </h1>
      </main>
    </>
  );
};

export default Home;
